Сделать доработки по ТЗ_6
KrisTinkaF/java-kanban pull request #1
Opened 2024-07-13 09:46 UTC by KrisTinkaF

Сделан двусвязный список для хранения последовательности просмотров задач, удаление из него нод реализовано через HashMap. Реализовано удаление из истории просмотров удаленных задач. Скорректированы тесты.

2024-07-13 15:45 UTC, EugeneLenkevich requested changes
Привет, Кристина! Спасибо за PR.

Отличная работа, все супер, но хотелось бы причесать тест :)
Все проверки стоит делать в самих тестовых методах (в тех же самых или может дополнительный тест сделать)

И, кстати, сборка красная, чекстайл ругается 

![image](https://github.com/user-attachments/assets/81716b8d-d755-49ba-8a5a-033368d5717b)

Тут поможет автоформатирование, сочетание клавиш Ctrl+Alt+L или через меню Code->Reformat Code. Пользуйся, очень удобная штука :)

2024-07-13 15:45 UTC, EugeneLenkevich commented on src/manager/InMemoryHistoryManager.java
> +        ArrayList<Task> tasks = new ArrayList<>();
List<Task> tasks = ...
Давай все таки использовать интерфейсы как типы переменных :)

2024-07-13 15:45 UTC, EugeneLenkevich commented on test/manager/InMemoryTaskManagerTest.java
> +        assertNotEquals(history, new ArrayList<>(),"История пустая.");
или так
asserFalse(history.isEmpty());

И, кстати, а зачем нужна эта проверка если ниже мы проверяем размер коллекции, есть ли смысл в такой проверке, может хватит одной :)

2024-07-13 15:45 UTC, EugeneLenkevich commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
В afterAll как то много проверок, по идее этот метод ничего не проверяет, вообще, он  по задумке чисто технический и производит очистку занятых ресурсов. Тут наверно лучше все проверки вынести в сами тесты, как и подготовку данных (можно кстати сделать отдельный метод для создания всех сущностей если чтобы не копировать в разных методах)

2024-07-13 18:13 UTC, KrisTinkaF commented on src/manager/InMemoryHistoryManager.java
> +        ArrayList<Task> tasks = new ArrayList<>();
Привет! А можно узнать почему так лучше? Чтобы в голове отложилось...

2024-07-13 18:13 UTC, KrisTinkaF commented on test/manager/InMemoryTaskManagerTest.java
> +        assertNotEquals(history, new ArrayList<>(),"История пустая.");
Хороший вопрос...))) Видимо, это было из разряда: "Лучше перебдеть..." исправлю

2024-07-13 18:37 UTC, KrisTinkaF commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
Вообще, так и хотелось, но не получилось :D У меня вместо метода с тестовыми сущностями beforeAll, а в afterAll все удаления... Окей, благодарю, переделаю, как я это поняла.

2024-07-14 09:29 UTC, EugeneLenkevich commented on src/manager/InMemoryHistoryManager.java
> +        ArrayList<Task> tasks = new ArrayList<>();
Основная идея в том что в случае интерфейсов у нас связи между модулями не такие жесткие. Мы можем поменять без каких то проблем одну реализацию на другую без изменения окружающего кода. Получается что код сможем собирать из "кубиков". 

Интерфейс - это контракт, задавая интерфейс мы говорим что у объекта есть вот такое конкретное поведение и внешний код завязывается на это поведение, а вот остальное поведение объекта в данном случае не имеет значения и внешний код к нему не имеет доступа вовсе.

А вот если будем ставить конкретные реализации, то не сможем потом без усилий заменить одну реализацию на другую потому что кто то обязательно завяжется на какие то специфические методы. 
Это как есть у нас usb-разьем (а это и есть интерфейс), мы в него можем воткнуть много разных устройств и все они будут работать. Если бы не было такого общего интерфейса нам бы пришлось иметь или кучу переходников или вообще проводками напрямую цеплять, что совсем не просто.

Это буковка L (Принцип подстановки Барбары Лисков) в SOLID 
https://habr.com/ru/companies/ruvds/articles/426413/

2024-07-14 09:35 UTC, EugeneLenkevich commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
Вот все верно, только в createTestTasks можно полностью пересоздавать менеджеры, тогда и чистить не придется и это будет надежней. Плюс оставить аннотацию @BeforeEach над методом подготовки чтобы не вызывать его руками. 
Вообще, достаточно поставить аннотации @BeforeEach и @AfterEach над твоими методами создания и очистки и тогда руками запускать ничего не надо будет

2024-07-14 09:38 UTC, EugeneLenkevich requested changes
Привет!
Давай все же тест добьем чтобы было совсем правильно. Самый простой способ - пересоздать полностью все менеджеры чтобы не мудрствовать как бы привести все в первоначальный вид 
Если все понятно, но некогда, то возвращай как есть, на следующем задании допилим :)

2024-07-14 17:53 UTC, KrisTinkaF commented on src/manager/InMemoryHistoryManager.java
> +        ArrayList<Task> tasks = new ArrayList<>();
Спасибо за развернутый ответ!

2024-07-14 18:57 UTC, KrisTinkaF commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
С пересозданием менеджеров вышло интересно. Счетчик задач не был частью конструктора, соответственно, при пересоздании менеджеров он обнулял список сохраненных задач, а вот нумерацию id продолжал и тесты посыпались. Я установила counter = 0 при создании менеджера тасков, а теперь призадумалась, правильная ли это реализация?

2024-07-15 03:27 UTC, EugeneLenkevich approved these changes
Во, все верно, и как проще стало :)

2024-07-15 06:04 UTC, EugeneLenkevich commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
Счетчик небось static, вот и не сбрасывается сам, руками занулить более чем нормально, ну или не проверять id :)

2024-07-15 11:43 UTC, KrisTinkaF commented on test/manager/InMemoryTaskManagerTest.java
> +    static void afterAll() {
даааа, он static) я даже не смекнула, спасибо!!

2024-07-15 11:44 UTC, merged