Реализовать функционал по ТЗ_7
KrisTinkaF/java-kanban pull request #2
Opened 2024-07-19 09:37 UTC by KrisTinkaF

Создан FileBackedTaskManager, который сохраняет задачи в файл и восстанавливает их из файла при запуске. Добавлены тесты.

2024-07-19 19:58 UTC, EugeneLenkevich requested changes
Привет, Кристина! Спасибо за PR.

В целом все верно, но хочется причесать исключения
Исключения бывают 

- проверяемые  - это штатные ситуации которые мы ожидаем по бизнес-процессу, но их надо как то обрабатывать, например в машине кончается бензин
- непроверяемые - ошибка в логике, не относящаяся к бизнес-процессу, под капотом задымилось

В нашей ситуации что непредвиденная ошибка при чтении данных, что ошибка при сохранении данных - критическая ситуация, с пользовательскими данными что то приключилось, тут стоит упасть чтобы пользователь был в курсе. 
Переделай, пожалуйста исключение в непроверяемое (RuntimeException) и добавь его вызов именно в  тех местах, где мы получаем непредвиденные ошибки при чтении или сохранении файла :)

2024-07-19 19:58 UTC, EugeneLenkevich commented on src/manager/FileBackedTaskManager.java
> +                System.out.println("Не смогли прочесть файл: " + exception.getMessage());
Тут стоит выкидывать наше непроверяемое исключение :) 
Если файл не удалось прочитать по какой либо причине, то приложение скорее всего находится в неизвестном или неконсистентном состоянии. Лучше сразу упасть чтобы пользователь знал что что-то пошло не так 

https://habr.com/ru/post/218325/

2024-07-19 19:58 UTC, EugeneLenkevich commented on src/manager/FileBackedTaskManager.java
> +        } catch (IOException e) {
А тут и ниже уже не надо ловить, обработка ошибок пусть будет происходить централизовано - в методе save, там и стоит исключения обрабатывать :)

2024-07-19 19:58 UTC, EugeneLenkevich commented on src/model/ManagerSaveException.java
> +public class ManagerSaveException extends IOException {
Тут стоит сделать непроверяемое исключение, extends RuntimeException

2024-07-20 09:46 UTC, KrisTinkaF commented on src/manager/FileBackedTaskManager.java
> +                System.out.println("Не смогли прочесть файл: " + exception.getMessage());
Привет! Спасибо за комментарии и ссылку! Тут у меня возникли проблемы в понимании как реализовать. В классе FileReader прописана возможность выброса FileNotFoundException, который является наследником IOException, соответственно я не могу просто заменить IOException на RuntimeException, среда ругается.

2024-07-20 10:48 UTC, KrisTinkaF commented on src/model/ManagerSaveException.java
> +public class ManagerSaveException extends IOException {
Done

2024-07-20 10:48 UTC, KrisTinkaF commented on src/manager/FileBackedTaskManager.java
> +        } catch (IOException e) {
Done

2024-07-20 10:50 UTC, KrisTinkaF commented on src/manager/FileBackedTaskManager.java
> +                System.out.println("Не смогли прочесть файл: " + exception.getMessage());
Вроде бы нашла решение

2024-07-20 10:58 UTC, EugeneLenkevich approved these changes
Ну смотри, RuntimeException в целом можно было не перехватывать, пусть бы так и падала.
Мы же тут ее перехватываем вместе с IOException, в целом так можно, но по сути мы не перехватываем, а трансформируем в наше исключение и кидаем дальше. В целом так можно делать, так как в принципе мы не ломаем общую схему работы исключений, так что пусть будет так, самое решение верно, но можно было и просто не ловить RuntimeException :)

Если интересно вот тут целое обсуждение этого момента https://stackoverflow.com/questions/1982533/when-is-it-ok-to-catch-a-runtimeexception

2024-07-20 11:39 UTC, merged