Сделать HTTP Server по ТЗ_9
KrisTinkaF/java-kanban pull request #4
Opened 2024-07-29 13:55 UTC by KrisTinkaF

Привет! Создала http сервер и обработчики. Но, по-моему, загнала себя в тупик( Не смогла понять как мне тесты запускать и фишку с тем, что теперь в классе сервера метод main. А класс Main теперь подлежит удалению? В общем запуталась. Отправляю, потому что время мое кончилось, но надежда на комментарии по ревью)))

2024-07-29 17:27 UTC, KrisTinkaF commented
Тесты добавила))

2024-07-29 18:06 UTC, EugeneLenkevich requested changes
Привет, Кристина! Спасибо за PR.

Супер что все удалось порешать и довести до ума :)

1. В целом main особо и не нужен, у нас есть тесты, однако, он и не мешает и, в свете того, что по этой теме это последнее задание, то уже без разницы, вот как проще пусть так и будет
2. Сериализатор gson лучше создать один раз, настроить и давать везде на него ссылку. Это может быть достаточно дорогая операция плюс лучше и проще когда объект создается только в одном определенном месте, допустим нам потребуется менять какую то настройку - придется же по всему коду искать :)
Как самый простой вариант можно[ статический метод ](https://habr.com/ru/companies/otus/articles/802717/)придумать под это дело 
3.  Лишние статики бы вычистить, с ними лучше вообще не связываться, ну на крайний случай константы. Потому что это потенциальная утечка памяти, как минимум 
4. Потом еще в тестах бы всю техническую историю по созданию запросов спрятать во вспомогательные методы

А в целом, конечно, вручную разбирать http довольно муторно, однако, потом будет проще, современные фреймворки делают это гораздо проще 
Посмотри по возможности что можно поправить, если времени не особо :)

2024-07-29 18:06 UTC, EugeneLenkevich commented on src/api/BaseHttpHandler.java
> +            Gson gson = gsonBuilder.create();
GsonBuilder gsonBuilder = new GsonBuilder();
            gsonBuilder.registerTypeAdapter(LocalDateTime.class, new LocalDateTimeTypeAdapter());
            gsonBuilder.setPrettyPrinting();
Gson gson = gsonBuilder.create();

Объект gson создается и настраивается каждый раз, это не особо оптимально, лучше его где то создать один раз а потом переиспользовать :)

2024-07-29 18:06 UTC, EugeneLenkevich commented on src/api/HttpTaskServer.java
> +    private static TaskManager fileBackedTaskManager;
1. А надо ли менеджер задач и менеджер истории делать статическими, они так в памяти болтаться будут даже если сервер остановится 
2. fileBackedTaskManager - лучше переименовать просто в taskManager, наверно не за чем эти лишние детали реализации указывать в имени :)

2024-07-29 18:06 UTC, EugeneLenkevich commented on src/api/TaskHandler.java
> +    private static TaskManager fileBackedTaskManager;
Тут тоже статик особо не нужен, а инициализация поля происходит в конструкторе :)

2024-07-29 18:06 UTC, EugeneLenkevich commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
Вместо того чтобы писать строкой этот json можно попробовать создать объект в коде, а потом сериализовать его с помощью нашего объекта gson :)

2024-07-29 18:06 UTC, EugeneLenkevich commented on test/api/HttpTaskServerTest.java
> +        URI url = URI.create("http://localhost:8080/history");
```
        URI url = URI.create("http://localhost:8080/history");
        HttpRequest request = HttpRequest.newBuilder()
                .uri(url)
                .GET()
                .build();
```

Что такое тест - это по сути описание бизнес-задачи, вот это все создание объекта запроса - технические детали, которые только отвлекают от понимания сути теста, по этому лучше их спрятать за вспомогательными методами, так тест станет проще и понятней, давай попробуем спрятать всю эту техническую историю :)

2024-07-29 19:22 UTC, KrisTinkaF commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
А что-то у меня так не выходит... Такой запрос он не ест...
Subtask subtask = new Subtask("Имя", "описание", LocalDateTime.of(2024, 7, 21, 9, 30), Duration.ofMinutes(30), taskManager.getById(13).getId());
        subtask.setStatus(Status.NEW);
        HttpClient client = HttpClient.newHttpClient();
        System.out.println("sub "+subtask);

        URI url = URI.create("http://localhost:8080/subtasks");
        HttpRequest request = HttpRequest.newBuilder()
                .uri(url)
                .POST(HttpRequest.BodyPublishers.ofString(gson.toJson(subtask)))
                .build();

2024-07-29 19:30 UTC, EugeneLenkevich commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
А ошибка то какая?

2024-07-29 19:45 UTC, KrisTinkaF commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
Не могу ничего поймать, только моя же ошибка 400...

2024-07-29 19:50 UTC, KrisTinkaF commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
Поняла что, но не поняла почему. На выходе получается почему-то саба с id = 0, по условиям мы пытаемся апдейтить, если есть id в запросе, но сабы с id = 0 нету и он падает.

2024-07-29 20:19 UTC, KrisTinkaF commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
В общем, проблема выглядела как-будто оно в toString(), потому что там мы выводим id, но он пока не присвоен, а значит, неинициализированный int будет 0, как я понимаю. Из интереса переписала toSting(), но проблема не решилась, потому что json все равно получился с 0. Если есть на этот счет совет, буду рада)
Вот что вывел лог:
sub SUBTASK;Имя;описание;NEW;2024-07-21T09:30;PT30M;13
sub json {
  "parentId": 13,
  "id": 0,
  "name": "Имя",
  "description": "описание",
  "status": "NEW",
  "duration": "PT30M",
  "startTime": "21-07-2024, 09:30"
}

Получено из этих строк:

Subtask subtask = new Subtask("Имя", "описание", LocalDateTime.of(2024, 7, 21, 9, 30), Duration.ofMinutes(30), taskManager.getById(13).getId());
        subtask.setStatus(Status.NEW);
        HttpClient client = HttpClient.newHttpClient();
        System.out.println("sub " + subtask);
        System.out.println("sub json " + gson.toJson(subtask));

toString() переопределила на:

@Override
    public String toString() {
        if (duration == null) {
            duration = Duration.ZERO;
        }
        if (id == 0) {
            return getType() +
                    ";" + name +
                    ";" + description +
                    ";" + status +
                    ";" + startTime +
                    ";" + duration +
                    ";";
        } else {
            return id +
                    ";" + getType() +
                    ";" + name +
                    ";" + description +
                    ";" + status +
                    ";" + startTime +
                    ";" + duration +
                    ";";
        }
    }

2024-07-30 03:42 UTC, EugeneLenkevich approved these changes
Привет, по тесту отписал ниже, с другой стороны стоит ли сильно закапываться, давай пойдем дальше, время если будет можно будет поковырять, мы все равно с этим дальше столкнемся, но более комплексно в рамках спринг бута

2024-07-30 03:42 UTC, EugeneLenkevich commented on test/api/HttpTaskServerTest.java
> +    private Gson creteGson() {
А у нас уже есть же этот метод, можно было его и использовать каким то образом :)

2024-07-30 03:42 UTC, EugeneLenkevich commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
А ошибка то какая :)
Вот так сходу ничего не понятно, тут надо подебажить, я твой проект так сходу открыть не могу, библиотеки надо все подтягивать, тут лучше сразу наставника спрашивать
А так можно было тест как раньше оставить тогда не критично

2024-07-30 06:08 UTC, KrisTinkaF commented on test/api/HttpTaskServerTest.java
> +                        "    \"type\":\"SUBTASK\",\n" +
Ошибки как таковой нет. Она в том, что 0 попадает в id при сериализации, а значит, мы попадаем на метод апдейта, а не создания. Вот по этому условию:

boolean hasId = jsonObject.has("id");
        try {
            Task task = gson.fromJson(body, Task.class);

            if (hasId) {
                taskManager.updateTask(task);
            } else {
                taskManager.createTask(task);
            }

Но в мапе не существует таски с id 0. Спрошу наставника, спасибо!

2024-07-30 14:41 UTC, merged